import type { Metadata } from "next";
import React from "react";
import { Container, Footer, Header } from "@/components/shared";

export const metadata: Metadata = {
  title: "StockSenseX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Container className="py-8">{children}</Container>
      <Footer />
    </>
  );
}