-- AlterTable
ALTER TABLE "User" ALTER COLUMN "provider" DROP NOT NULL,
ALTER COLUMN "provider" SET DATA TYPE TEXT,
ALTER COLUMN "providerId" DROP NOT NULL,
ALTER COLUMN "providerId" SET DATA TYPE TEXT;
