import type { Metadata } from "next";
import React from "react";
import { AppSidebar, Container, Footer } from "@/components/shared";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
  TooltipProvider,
} from "@/components/ui";
import { getUserSession } from "@/lib/get-user-session";
import { prisma } from "@/prisma/prisma";

export const metadata: Metadata = {
  title: "Workspace | StockSenseX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await getUserSession();

  if (!session) {
    return (
      <SidebarProvider>
        <TooltipProvider>
          <AppSidebar user={undefined} />
          <SidebarInset className="items-center bg-accent">
            <SidebarTrigger className="mt-1 ml-1 self-start" />
            <Container className="py-8">
              {children}
              {modal}
            </Container>
            <Footer />
          </SidebarInset>
        </TooltipProvider>
      </SidebarProvider>
    );
  }

  const user =
    (await prisma.user.findFirst({
      where: {
        id: Number(session.id),
      },
    })) || undefined;

  return (
    <SidebarProvider>
      <TooltipProvider>
        <AppSidebar user={user} />
        <SidebarInset className="items-center bg-accent">
          <SidebarTrigger className="mt-1 ml-1 self-start" />
          <Container className="py-8">
            {children}
            {modal}
          </Container>
          <Footer />
        </SidebarInset>
      </TooltipProvider>
    </SidebarProvider>
  );
}